### ISSUE TITLE
DSEfix not working for me.

### ISSUE THREAD

**Issue by Newrender** [hfiref0x/DSEFix#3]
So....

I need to load a driver in for a injector for a game.
I downloaded DSEfix and ran it as administrator
Directly afterwards i tried to load in the driver and i got this:

http://gyazo.com/61cd920d894053bbab4c7b62b4d79e72

So i guess DSEfix is not working for me.
Anyone suggestments?

**Comment by hfiref0x** [comment]
Very informative post. No information about system, configuration, no debug output (from DbgView) to see if program worked or not.

**Comment by Newrender** [comment]
System:

Windows 7 64 bit
CPU: Intil i5 4670k
Ram: 16G

I have used the dbgview and this is what i get when i run the program:

00000204	82.06834412	[2288] [DF] DSEFix v1.1.0 started	
00000205	82.06835175	[2288] [DF] (c) 2014 - 2015 DSEFix Project	
00000207	82.06839752	[2288] [DF] DSE will be disabled	
00000274	82.74853516	[2316] [<03:23:2015:09:26:22:151>GameScannerService(RzProcessManager)(0x90c)(0x464)] RMLUser::ProcessInfoEvent - Process End - PID 0x8f0 Parent 0x6a4 Path C:\Users\Jesse\Desktop\dsefix.exe

**Comment by hfiref0x** [comment]
This log is incomplete. Do you have VirtualBox installed?

**Comment by Newrender** [comment]
Erm.... no i dont.

I filtered the log to only show up DSEfix that might be the reason why its incomplete

**Comment by hfiref0x** [comment]
Then without debuggin on your machine it is impossible to figure out solution.

**Comment by Newrender** [comment]
Once im home ill debug again but then without filtering and give better information

**Comment by Newrender** [comment]
just tried it again, now something with the virtual box pops up:

00000153	17.85684776	[9024] [DF] DSEFix v1.1.0 started	
00000154	17.85686302	[9024] [DF] (c) 2014 - 2015 DSEFix Project	
00000155	17.85687256	[9024] [DF] Supported x64 OS : Vista / 7 / 8 / 8.1 / 10	
00000156	17.85688972	[9024] [DF] DSE will be disabled	
00000157	17.88878250	[2316] [<03:23:2015:16:52:17:882>GameScannerService(RzProcessManager)(0x90c)(0x464)] RMLUser::ProcessInfoEvent - Process Start - PID 0x2010 Parent 0x578 Path C:\Program Files\NVIDIA Corporation\Display\nvtray.exe	
00000158	17.88986015	[2316]  	
00000159	17.89951134	[2316] [<03:23:2015:16:52:17:891>GameScannerService(RzProcessManager)(0x90c)(0x464)]  ProcessUtilities::IsChildOfRunningGame (recursion level: [0])	
00000160	17.89961052	[2316]  	
00000214	17.93107414	[2316]  	
00000215	18.17273521	[9024] [DF] Vulnerable VirtualBox driver loaded	
00000216	18.17317581	[9024] [DF] Windows v6.1	
00000217	18.17320251	[9024] [DF] Target module C:\Windows\system32\ntoskrnl.exe	
00000218	18.17325783	[9024] [DF] Module base FFFFF80002E1F000	
00000219	18.19229126	[9024] [DF] Apply patch to address FFFFF800030446D8	
00000220	18.19329071	[9024] [DF] Kernel memory patched	
00000221	18.19355583	[9024] [DF] Cleaning up	
00000222	18.19600487	[9024] [DF] Finish

**Comment by hfiref0x** [comment]
This log indicates DSE is successfully turned off which means you can now load unsigned drivers. If you have something (different from 1st post tool) with unsigned driver try it for test.

**Comment by Newrender** [comment]
I will make a recordment by what im doing

**Comment by Newrender** [comment]
Here you go:

https://www.youtube.com/watch?v=xKDZupGb2v8&feature=youtu.be

**Comment by hfiref0x** [comment]
This "Injector" or whatever, doesn't it supposed to be runned with admin rights? You cannot write to HKLM (for driver installation) without admin.

**Comment by Newrender** [comment]
Its the same when i run it as admin

**Comment by Newrender** [comment]
Maybe it is because im using windows 7 Home version

**Comment by hfiref0x** [comment]
Windows edition doesn't matter. In fact it is Injector trouble, DSE is turned off according to log. You can try to load this unsigned driver manually, using sc command (sc create), http://stackoverflow.com/questions/7828663/how-do-i-install-a-custom-windows-driver

**Comment by Newrender** [comment]
The driver is build in that injector or something, so i dont have acces to this .sys file

**Comment by hfiref0x** [comment]
test

**Comment by TheAifam5** [comment]
You must first run patch and then run your Xenos...
