### ISSUE TITLE
Windows Requires a Digitally Signed Driver

### ISSUE THREAD

**Issue by pRealTable** [hfiref0x/DSEFix#5]
Hi,  @hfiref0x,
I am using your project, i can disable Driver Singing Enforcement, i can load driver but..
When i load my driver windows says, "Windows Requires a Digitally Signed Driver"..
Screen shot added.. 
![error](https://cloud.githubusercontent.com/assets/11784541/7045017/2af5cc7e-de02-11e4-8e70-b86658ac6875.jpg)

**Comment by hfiref0x** [comment]
Excuse me, how this is related to Dsefix? Do not want these messages - sign your driver.

**Comment by pRealTable** [comment]
I see. thanks.
