### ISSUE TITLE
bug in disasm of 3 and 5 byte nop's

### ISSUE THREAD

**Issue by AlexanderBagel** [hfiref0x/DSEFix#7]
# include <Windows.h>
# include <stdio.h>
# include <tchar.h>
# include "ldasm.h"
# include "ldasm.c"

int tmain(int argc, TCHAR\* argv[])
{
 ldasm_data d;
 byte codebuff[17 + 5 + 3] = 
  { 0x55, 0x53, 0x48, 0x83, 0xEC, 0x58, 0x48, 0x8B, 0xEC, 0x48, 0xC7, 0x45, 0x38, 0x00, 0x00, 0x00, 0x00, 0x0f, 0x1f, 0x44, 0x00, 0x00, 0x0f, 0x1f, 0x00 };
 /*
 55               push rbp
 53               push rbx
 4883EC58         sub rsp,$58
 488BEC           mov rbp,rsp
 48C7453800000000 mov qword ptr [rbp+$38],$0000000000000000
 0F1F440000       nop dword ptr ds:[rax+rax]
 0F1F00           nop dword ptr ds:[rax]                  |
 */
 unsigned int i = 0;
 i += ldasm(&codebuff[i], &d, 1); // push rbp - OK
 i += ldasm(&codebuff[i], &d, 1); // push rbx - OK
 i += ldasm(&codebuff[i], &d, 1); // sub rsp,$58 - OK
 i += ldasm(&codebuff[i], &d, 1); // mov rbp,rsp - OK
 i += ldasm(&codebuff[i], &d, 1); // mov qword ptr... - OK
 // ERROR!!!!!!!!
 i += ldasm(&codebuff[i], &d, 1); // expected 5 byte for "nop dword ptr ds:[rax+rax]", but actual is 2 byte
 i += ldasm(&codebuff[i], &d, 1); // then garbage with REX (3 byte)
 i += ldasm(&codebuff[i], &d, 1); // expected 3 byte for "nop dword ptr ds:[rax]", but actual is 2 byte
 i += ldasm(&codebuff[i], &d, 1); // error - out of range (ldasm() return 2)
 return 0;
}

**Comment by hfiref0x** [comment]
This ldasm is from https://github.com/vol4ok/libsplice/, I would suggest you contact author with this.
